from __future__ import annotations

from collections.abc import Iterable

DEFAULT_MCP_TOOL_CANDIDATES: tuple[str, ...] = (
    "query_ira",
    "quick_answer",
    "discover_tools_for_query",
    "search_knowledge",
    "search_crm",
    "get_pipeline_summary",
    "sync_crm_apollo",
    "enrich_contact_apollo",
    "search_people_apollo",
    "draft_email",
    "create_google_meet_invite",
    "check_google_calendar_availability",
    "schedule_google_meet_best_slot",
    "ingest_document",
    "parse_document_ai",
    "get_agent_list",
    "ask_agent",
    "search_emails",
    "read_email_thread",
    "recall_memory",
    "store_memory",
    "get_conversation_history",
    "check_relationship",
    "check_goals",
    "get_deal",
    "list_deals",
    "create_contact",
    "update_deal",
    "get_stale_leads",
    "find_related_entities",
    "find_company_contacts",
    "find_company_quotes",
    "submit_correction",
    "web_search",
    "searchapi_search",
    "search_newsdata",
    "scrape_url",
    "fetch_youtube_transcript",
    "maps_geocode",
    "maps_driving_route",
    "maps_places_text_search",
    "maps_places_nearby_search",
    "maps_place_details",
    "get_project_status",
    "get_overdue_milestones",
    "plan_task",
    "execute_phase",
    "generate_report",
    "get_task_status",
    "abort_task",
    "list_tasks",
    "get_task_events",
    "retry_task",
    "trigger_dream_mode",
    "get_knowledge_gaps",
    "search_cursor_sessions",
    "invoke_claude_code",
    "git_ship_status",
    "convene_board_meeting",
    "get_system_status",
    "math_mode_analyze_account",
    "math_mode_rank_operator_queue",
    "math_mode_explain_score",
    "math_mode_learn_weights",
    "math_mode_training_report",
    "math_mode_offline_backtest",
    "math_mode_ops_cycle",
    "math_mode_bootstrap_training_dataset",
    "math_mode_promote_weights",
    "formulas_list_registry",
    "formulas_reconcile",
    "formulas_promote_checklist",
    "formulas_schedule_hints",
    "formulas_refit",
    "get_account_brief",
    "next_best_account_action",
    "deal_risk_audit",
    "stage_exit_criteria_check",
    "evidence_backing_check",
    "objection_rebuttal_generator",
    "quote_competitiveness_check",
    "buying_committee_map",
    "stalled_deal_revival_playbook",
)


def rank_mcp_tools(query: str, tool_names: Iterable[str]) -> list[str]:
    """Rank MCP tools for a query using lightweight keyword heuristics."""
    q = (query or "").lower()
    ordered_tools = sorted(set(tool_names))
    scores: dict[str, int] = {name: 0 for name in ordered_tools}

    keyword_map: dict[str, tuple[str, ...]] = {
        "email": ("search_emails", "read_email_thread", "draft_email", "query_ira"),
        "mail": ("search_emails", "read_email_thread", "draft_email", "query_ira"),
        "gmail": ("search_emails", "read_email_thread", "query_ira"),
        "calendar": ("create_google_meet_invite", "query_ira"),
        "availability": (
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "free busy": (
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "free/busy": (
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "book first free slot": (
            "schedule_google_meet_best_slot",
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "one shot schedule": (
            "schedule_google_meet_best_slot",
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "schedule invite": (
            "schedule_google_meet_best_slot",
            "create_google_meet_invite",
            "query_ira",
        ),
        "calendar conflict": (
            "check_google_calendar_availability",
            "create_google_meet_invite",
            "query_ira",
        ),
        "google meet": ("create_google_meet_invite", "query_ira"),
        "meet invite": ("create_google_meet_invite", "draft_email", "query_ira"),
        "schedule meeting": ("create_google_meet_invite", "draft_email", "query_ira"),
        "meeting invite": ("create_google_meet_invite", "draft_email", "query_ira"),
        "thread": ("read_email_thread", "search_emails"),
        "crm": ("search_crm", "list_deals", "get_deal", "get_pipeline_summary", "query_ira"),
        "deal": (
            "list_deals",
            "get_deal",
            "update_deal",
            "get_pipeline_summary",
            "deal_risk_audit",
            "stage_exit_criteria_check",
            "stalled_deal_revival_playbook",
            "query_ira",
        ),
        "deal risk": ("deal_risk_audit", "get_deal", "get_account_brief", "query_ira"),
        "risk audit": ("deal_risk_audit", "get_account_brief", "query_ira"),
        "stage exit": ("stage_exit_criteria_check", "deal_risk_audit", "get_deal"),
        "stage gate": ("stage_exit_criteria_check", "deal_risk_audit", "update_deal"),
        "move stage": ("stage_exit_criteria_check", "deal_risk_audit", "get_deal"),
        "stalled deal": ("stalled_deal_revival_playbook", "deal_risk_audit", "get_stale_leads"),
        "revival playbook": ("stalled_deal_revival_playbook", "deal_risk_audit"),
        "re-engage": ("stalled_deal_revival_playbook", "persuasion_sprint", "get_account_brief"),
        "buying committee": ("buying_committee_map", "find_company_contacts", "get_account_brief"),
        "stakeholder map": (
            "buying_committee_map",
            "find_company_contacts",
            "search_people_apollo",
        ),
        "objection": ("objection_rebuttal_generator", "list_outbound_proof_artifacts", "query_ira"),
        "price objection": ("objection_rebuttal_generator", "quote_competitiveness_check"),
        "rebuttal": ("objection_rebuttal_generator", "list_outbound_proof_artifacts"),
        "quote competitiveness": ("quote_competitiveness_check", "prepare_machinecraft_quote"),
        "margin risk": ("quote_competitiveness_check", "deal_risk_audit"),
        "evidence check": ("evidence_backing_check", "list_outbound_proof_artifacts"),
        "proof check": ("evidence_backing_check", "list_outbound_proof_artifacts", "draft_email"),
        "backed claims": ("evidence_backing_check", "list_outbound_proof_artifacts"),
        "next best action": (
            "next_best_account_action",
            "get_account_brief",
            "math_mode_analyze_account",
        ),
        "next step": ("next_best_account_action", "get_account_brief", "math_mode_analyze_account"),
        "account brief": (
            "get_account_brief",
            "next_best_account_action",
            "math_mode_analyze_account",
        ),
        "pipeline": ("get_pipeline_summary", "list_deals", "query_ira"),
        "contact": ("search_crm", "create_contact", "find_company_contacts", "query_ira"),
        "company": ("search_crm", "find_company_contacts", "find_company_quotes", "query_ira"),
        "apollo": ("sync_crm_apollo", "enrich_contact_apollo", "search_people_apollo", "query_ira"),
        "enrich crm": ("sync_crm_apollo", "query_ira"),
        "prospect": ("search_people_apollo", "search_crm", "query_ira"),
        "quote": ("find_company_quotes", "get_deal", "list_deals", "query_ira"),
        "math": (
            "math_mode_analyze_account",
            "math_mode_explain_score",
            "math_mode_rank_operator_queue",
            "math_mode_learn_weights",
            "math_mode_training_report",
            "math_mode_ops_cycle",
            "math_mode_bootstrap_training_dataset",
            "get_account_brief",
        ),
        "mathematics": (
            "math_mode_analyze_account",
            "math_mode_explain_score",
            "math_mode_rank_operator_queue",
        ),
        "score": (
            "math_mode_analyze_account",
            "math_mode_explain_score",
            "math_mode_rank_operator_queue",
            "persuasion_sprint",
        ),
        "scoring": (
            "math_mode_analyze_account",
            "math_mode_explain_score",
            "math_mode_rank_operator_queue",
        ),
        "learn weights": ("math_mode_learn_weights", "math_mode_explain_score"),
        "train weights": ("math_mode_learn_weights", "math_mode_explain_score"),
        "learn from outcomes": ("math_mode_learn_weights", "math_mode_rank_operator_queue"),
        "offline backtest": ("math_mode_offline_backtest", "math_mode_training_report"),
        "math backtest": ("math_mode_offline_backtest", "math_mode_training_report"),
        "backtest math": ("math_mode_offline_backtest", "math_mode_learn_weights"),
        "promote weights": ("math_mode_promote_weights", "formulas_promote_checklist"),
        "promote math": ("math_mode_promote_weights", "math_mode_offline_backtest"),
        "formula reconcile": ("formulas_reconcile", "formulas_list_registry"),
        "reconcile formulas": ("formulas_reconcile", "formulas_promote_checklist"),
        "refit scatter": ("formulas_refit", "formulas_list_registry"),
        "refit matchmaker": ("formulas_refit", "formulas_list_registry"),
        "training report": ("math_mode_training_report", "math_mode_learn_weights"),
        "calibration report": ("math_mode_training_report", "math_mode_learn_weights"),
        "drift report": ("math_mode_training_report", "math_mode_learn_weights"),
        "math ops": ("math_mode_ops_cycle", "math_mode_training_report"),
        "ops cycle": ("math_mode_ops_cycle", "math_mode_rank_operator_queue"),
        "daily math ops": ("math_mode_ops_cycle", "math_mode_training_report"),
        "bootstrap training": ("math_mode_bootstrap_training_dataset", "math_mode_learn_weights"),
        "seed training data": ("math_mode_bootstrap_training_dataset", "math_mode_learn_weights"),
        "readiness": ("math_mode_analyze_account", "math_mode_explain_score"),
        "cadence": ("math_mode_analyze_account", "math_mode_rank_operator_queue"),
        "priority": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "ranking": ("math_mode_rank_operator_queue",),
        "rank accounts": ("math_mode_rank_operator_queue", "get_account_brief"),
        "operator queue": ("math_mode_rank_operator_queue", "operator_inbox_summary"),
        "rank queue": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "prioritize queue": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "prioritise queue": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "queue priority": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "prioritize accounts": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "prioritise accounts": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "rank leads": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "rank opportunities": ("math_mode_rank_operator_queue", "math_mode_analyze_account"),
        "triangulate score": ("get_account_brief", "math_mode_analyze_account"),
        "fourier": ("math_mode_analyze_account", "math_mode_explain_score"),
        "trigonometry": ("math_mode_explain_score", "math_mode_analyze_account"),
        "fuzzy": ("math_mode_explain_score", "math_mode_analyze_account"),
        "nnfl": ("math_mode_explain_score", "math_mode_analyze_account"),
        "memory": ("recall_memory", "store_memory", "get_conversation_history", "query_ira"),
        "remember": ("recall_memory", "store_memory", "query_ira"),
        "web": (
            "web_search",
            "searchapi_search",
            "search_newsdata",
            "fetch_youtube_transcript",
            "scrape_url",
            "query_ira",
        ),
        "youtube": ("fetch_youtube_transcript", "scrape_url", "web_search", "query_ira"),
        "transcript": ("fetch_youtube_transcript", "query_ira"),
        "news": ("search_newsdata", "web_search", "query_ira"),
        "headline": ("search_newsdata", "web_search", "query_ira"),
        "searchapi": ("searchapi_search", "web_search", "query_ira"),
        "bing": ("searchapi_search", "web_search", "query_ira"),
        "research": (
            "web_search",
            "searchapi_search",
            "search_newsdata",
            "search_knowledge",
            "fetch_youtube_transcript",
            "scrape_url",
            "query_ira",
        ),
        "geocode": ("maps_geocode", "query_ira"),
        "coordinates": ("maps_geocode", "query_ira"),
        "google maps": (
            "maps_places_text_search",
            "maps_geocode",
            "maps_driving_route",
            "query_ira",
        ),
        "driving time": ("maps_driving_route", "query_ira"),
        "distance between": ("maps_driving_route", "query_ira"),
        "directions": ("maps_driving_route", "query_ira"),
        "places text": ("maps_places_text_search", "query_ira"),
        "text search": ("maps_places_text_search", "web_search", "query_ira"),
        "businesses near": ("maps_places_text_search", "query_ira"),
        "manufacturing near": ("maps_places_text_search", "web_search", "query_ira"),
        "thermoforming": (
            "maps_places_text_search",
            "maps_places_nearby_search",
            "web_search",
            "search_knowledge",
            "query_ira",
        ),
        "nearby": ("maps_places_nearby_search", "maps_places_text_search", "query_ira"),
        "radius": ("maps_places_nearby_search", "query_ira"),
        "place details": ("maps_place_details", "maps_places_text_search", "query_ira"),
        "knowledge": ("search_knowledge", "find_related_entities", "query_ira"),
        "lead time": ("quick_answer", "search_knowledge", "query_ira"),
        "spec": ("quick_answer", "search_knowledge", "query_ira"),
        "what is": ("quick_answer", "search_knowledge", "query_ira"),
        "ocr": ("parse_document_ai", "ingest_document", "query_ira"),
        "document ai": ("parse_document_ai", "query_ira"),
        "scanned pdf": ("parse_document_ai", "ingest_document", "query_ira"),
        "invoice parse": ("parse_document_ai", "query_ira"),
        "form parse": ("parse_document_ai", "query_ira"),
        "graph": (
            "find_related_entities",
            "find_company_contacts",
            "find_company_quotes",
            "query_ira",
        ),
        "project": ("get_project_status", "get_overdue_milestones", "query_ira"),
        "task": (
            "plan_task",
            "execute_phase",
            "generate_report",
            "abort_agent_loop_plan",
            "list_tasks",
            "query_ira",
        ),
        "report": ("plan_task", "generate_report", "query_ira"),
        "agent": ("ask_agent", "get_agent_list", "query_ira"),
        "status": ("get_system_status", "query_ira"),
        "health": ("get_system_status", "query_ira"),
        "session": ("search_cursor_sessions", "get_conversation_history", "query_ira"),
        "sessions": ("search_cursor_sessions", "query_ira"),
        "cursor": ("search_cursor_sessions", "query_ira"),
        "graphe": ("search_cursor_sessions", "query_ira"),
        "logged": ("search_cursor_sessions", "query_ira"),
        "recall": ("search_cursor_sessions", "recall_memory", "query_ira"),
        "claude code": ("invoke_claude_code", "query_ira"),
        "claude-code": ("invoke_claude_code", "query_ira"),
        "implement": ("invoke_claude_code", "ask_agent", "query_ira"),
        "refactor": ("invoke_claude_code", "ask_agent", "query_ira"),
        "terminal": ("invoke_claude_code", "query_ira"),
        "subprocess": ("invoke_claude_code", "query_ira"),
        "git status": ("git_ship_status", "query_ira"),
        "working tree": ("git_ship_status", "query_ira"),
        "porcelain": ("git_ship_status", "query_ira"),
        "vapi": (
            "prepare_vapi_outbound",
            "vapi_outbound_dial",
            "vapi_outbound_fetch_call",
            "vapi_outbound_process_call",
            "vapi_outbound_status",
            "query_ira",
        ),
        "outbound call": (
            "prepare_vapi_outbound",
            "vapi_outbound_dial",
            "vapi_outbound_process_call",
            "query_ira",
        ),
        "dial": (
            "vapi_outbound_dial",
            "prepare_vapi_outbound",
            "query_ira",
        ),
        "phone call": (
            "prepare_vapi_outbound",
            "vapi_outbound_process_call",
            "prepare_na_call",
            "query_ira",
        ),
    }

    for key, candidates in keyword_map.items():
        if key in q:
            for idx, name in enumerate(candidates):
                if name in scores:
                    scores[name] += max(1, 3 - idx)

    # Keep broad fallback tools near the top for generic prompts.
    for name in ("query_ira", "quick_answer", "search_knowledge", "ask_agent", "get_system_status"):
        if name in scores:
            scores[name] += 1

    return sorted(scores.keys(), key=lambda name: (-scores[name], name))


def is_low_confidence_response(response: str) -> bool:
    """Heuristic marker for low-confidence / unavailable results."""
    text = (response or "").lower()
    markers = (
        "not available",
        "i don't know",
        "i do not know",
        "unable to",
        "couldn't find",
        "cannot find",
        "insufficient",
        "not enough information",
        "uncertain",
    )
    return any(marker in text for marker in markers)
