"""Pantheon — Brain OS starter orchestrator (generated by export_brain_os.py)."""

from __future__ import annotations

import asyncio
import json
import logging
from collections.abc import Awaitable, Callable
from typing import Any

from brain_os.agents.aegis import Aegis
from brain_os.agents.aletheia import Aletheia
from brain_os.agents.alexandros import Alexandros
from brain_os.agents.artemis import Artemis
from brain_os.agents.athena import Athena
from brain_os.agents.atlas import Atlas
from brain_os.agents.calliope import Calliope
from brain_os.agents.clio import Clio
from brain_os.agents.gapper import Gapper
from brain_os.agents.graphe import Graphe
from brain_os.agents.iris import Iris
from brain_os.agents.metis import Metis
from brain_os.agents.mnemon import Mnemon
from brain_os.agents.mnemosyne import Mnemosyne
from brain_os.agents.nemesis import Nemesis
from brain_os.agents.plutus import Plutus
from brain_os.agents.prometheus import Prometheus
from brain_os.agents.sophia import Sophia
from brain_os.agents.sphinx import Sphinx
from brain_os.agents.vera import Vera
from brain_os.agents.base_agent import BaseAgent
from brain_os.agents.model_tiers import apply_model_profile_to_agent
from brain_os.brain.deterministic_router import DeterministicRouter
from brain_os.brain.retriever import UnifiedRetriever
from brain_os.config import Settings, get_settings
from brain_os.data.models import BoardMeetingMinutes
from brain_os.exceptions import ToolExecutionError
from brain_os.message_bus import MessageBus
from brain_os.skills import SKILL_MATRIX
from brain_os.skills.handlers import use_skill

logger = logging.getLogger(__name__)

_AGENT_CLASSES: list[type[BaseAgent]] = [
    Aegis,
    Aletheia,
    Alexandros,
    Artemis,
    Athena,
    Atlas,
    Calliope,
    Clio,
    Gapper,
    Graphe,
    Iris,
    Metis,
    Mnemon,
    Mnemosyne,
    Nemesis,
    Plutus,
    Prometheus,
    Sophia,
    Sphinx,
    Vera,
]


def resolve_revenue_agent_names(settings: Settings | None = None) -> set[str] | None:
    """Brain OS skeleton: always load the full starter roster."""
    _ = settings
    return None


def get_pantheon_registry_public_snapshot() -> dict[str, int | str]:
    """Static Pantheon registration: specialist agent count and comma-separated name preview."""
    names = sorted(c.name for c in _AGENT_CLASSES)
    joined = ",".join(names)
    preview = joined if len(joined) <= 192 else f"{joined[:189]}…"
    return {
        "registered_agent_count": len(_AGENT_CLASSES),
        "agent_names_preview": preview,
        "starter_roster": True,
    }


class Pantheon:
    """Top-level orchestrator that ties agents, brain, and bus together."""

    def __init__(
        self,
        retriever: UnifiedRetriever,
        bus: MessageBus | None = None,
    ) -> None:
        self._bus = bus or MessageBus()
        self._retriever = retriever
        self._router = DeterministicRouter()

        active_names = resolve_revenue_agent_names()
        self._agents: dict[str, BaseAgent] = {}
        for cls in _AGENT_CLASSES:
            if active_names is not None and cls.name not in active_names:
                continue
            agent = cls(retriever=retriever, bus=self._bus)
            apply_model_profile_to_agent(agent)
            self._agents[agent.name] = agent

        self._athena: Athena = self._agents["athena"]  # type: ignore[assignment]

    def inject_services(self, services: dict[str, Any]) -> None:
        """Propagate shared services (CRM, PricingEngine, etc.) to all agents."""
        for agent in self._agents.values():
            agent.inject_services(services)
        logger.info(
            "Injected services into %d agents: %s",
            len(self._agents),
            sorted(services),
        )

    @property
    def router(self) -> DeterministicRouter:
        """Public access to the deterministic router."""
        return self._router

    @property
    def retriever(self) -> UnifiedRetriever:
        """Public access to the unified retriever."""
        return self._retriever

    # ── lifecycle ────────────────────────────────────────────────────────

    async def start(self) -> None:
        await self._bus.start()
        logger.info("Pantheon started with %d agents", len(self._agents))

    async def stop(self) -> None:
        await self._bus.stop()
        logger.info("Pantheon stopped")

    async def __aenter__(self) -> Pantheon:
        await self.start()
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.stop()

    # ── main entry point ─────────────────────────────────────────────────

    async def process(
        self,
        query: str,
        context: dict[str, Any] | None = None,
        on_progress: Callable[[dict[str, Any]], Awaitable[None]] | None = None,
    ) -> str:
        """Process a user query and return the final response.

        1. Try the deterministic router for a fast-path match.
        2. If no match, ask Athena to route via LLM.
        3. Dispatch to the selected agents and synthesise.
        """
        ctx = context or {}

        routing = self._router.route(query)
        if routing:
            return await self._dispatch_routed(query, routing, ctx, on_progress)

        return await self._dispatch_athena(query, ctx, on_progress)

    # ── routing strategies ───────────────────────────────────────────────

    async def _dispatch_routed(
        self,
        query: str,
        routing: dict[str, Any],
        context: dict[str, Any],
        on_progress: Callable[[dict[str, Any]], Awaitable[None]] | None = None,
    ) -> str:
        """Dispatch to agents selected by the deterministic router."""
        requested_names = routing["required_agents"]
        agent_names = [name for name in requested_names if name in self._agents]
        if not agent_names:
            logger.info(
                "Deterministic route resolved to inactive agents %s; falling back to Athena",
                requested_names,
            )
            agent_names = ["athena"]
        logger.info(
            "Deterministic route: %s -> %s",
            routing["intent"],
            agent_names,
        )

        ctx = {**context}
        if on_progress:
            ctx["_on_progress"] = on_progress

        if len(agent_names) == 1:
            agent = self._agents.get(agent_names[0])
            if agent:
                if on_progress:
                    await on_progress(
                        {
                            "type": "agent_started",
                            "agent": agent_names[0],
                            "role": getattr(agent, "role", ""),
                        }
                    )
                result = await agent.handle(query, ctx)
                result = result or "(No output)"
                if on_progress:
                    await on_progress(
                        {
                            "type": "agent_done",
                            "agent": agent_names[0],
                            "preview": str(result)[:200],
                        }
                    )
                return result

        responses = await self._gather_responses(agent_names, query, ctx, on_progress)

        if len(responses) == 1:
            return next(iter(responses.values()))

        if on_progress:
            await on_progress({"type": "synthesizing", "agent": "athena"})
        synthesis_timeout = get_settings().app.athena_synthesis_timeout
        try:
            return await asyncio.wait_for(
                self._athena.handle(query, {"agent_responses": responses}),
                timeout=synthesis_timeout,
            )
        except TimeoutError:
            logger.warning(
                "Athena synthesis timed out after %ds, returning concatenated responses",
                synthesis_timeout,
            )
            return "\n\n---\n\n".join(f"**{name}:** {resp}" for name, resp in responses.items())

    async def _dispatch_athena(
        self,
        query: str,
        context: dict[str, Any],
        on_progress: Callable[[dict[str, Any]], Awaitable[None]] | None = None,
    ) -> str:
        """Let Athena decide which agents to consult via LLM."""
        logger.info("LLM routing via Athena")
        if on_progress:
            await on_progress({"type": "routing", "agent": "athena"})

        ctx = {**context}
        if on_progress:
            ctx["_on_progress"] = on_progress

        routing_response = await self._athena.handle(query, ctx)

        agent_names = self._parse_agent_list(routing_response)
        if not agent_names:
            return routing_response

        responses = await self._gather_responses(agent_names, query, ctx, on_progress)
        if len(responses) == 1:
            return next(iter(responses.values()))

        if on_progress:
            await on_progress({"type": "synthesizing", "agent": "athena"})
        synthesis_timeout = get_settings().app.athena_synthesis_timeout
        try:
            return await asyncio.wait_for(
                self._athena.handle(query, {"agent_responses": responses}),
                timeout=synthesis_timeout,
            )
        except TimeoutError:
            logger.warning(
                "Athena synthesis timed out after %ds, returning concatenated responses",
                synthesis_timeout,
            )
            return "\n\n---\n\n".join(f"**{name}:** {resp}" for name, resp in responses.items())

    # ── board meeting mode ───────────────────────────────────────────────

    async def board_meeting(
        self,
        topic: str,
        participants: list[str] | None = None,
    ) -> BoardMeetingMinutes:
        """Run a board meeting where multiple agents discuss a topic.

        Each participant contributes their perspective, then Athena
        synthesises a final decision.
        """
        agent_names = participants or list(self._agents.keys())
        agent_names = [n for n in agent_names if n in self._agents and n != "athena"]

        contributions = await self._gather_responses(agent_names, topic, {})

        synthesis = await self._athena.handle(
            topic,
            {"agent_responses": contributions},
        )

        return BoardMeetingMinutes(
            topic=topic,
            participants=["athena"] + list(contributions.keys()),
            contributions=contributions,
            synthesis=synthesis,
        )

    # ── helpers ──────────────────────────────────────────────────────────

    async def _gather_responses(
        self,
        agent_names: list[str],
        query: str,
        context: dict[str, Any],
        on_progress: Callable[[dict[str, Any]], Awaitable[None]] | None = None,
    ) -> dict[str, str]:
        """Run agents concurrently (up to max_parallel_agents at a time) and collect their responses.

        Each agent gets a per-agent "slot" timeout (agent_timeout) to return the best possible answer.
        Athena receives all responses then has her own synthesis timeout to package the answer for Cursor/API.
        """
        settings = get_settings()
        agent_timeout = settings.app.agent_timeout
        max_parallel = max(1, settings.app.max_parallel_agents)
        semaphore = asyncio.Semaphore(max_parallel)

        ctx = {**context}
        if on_progress and "_on_progress" not in ctx:
            ctx["_on_progress"] = on_progress

        responses: dict[str, str] = {}

        async def _run_agent(name: str) -> tuple[str, str]:
            async with semaphore:  # Cap parallel sub-agents (e.g. up to 5 at a time)
                agent = self._agents.get(name)
                if not agent:
                    return name, f"(Agent '{name}' not found)"
                if on_progress:
                    await on_progress(
                        {"type": "agent_started", "agent": name, "role": getattr(agent, "role", "")}
                    )
                _timeout = getattr(agent, "timeout", None) or agent_timeout
                try:
                    response = await asyncio.wait_for(
                        agent.handle(query, {**ctx}),
                        timeout=_timeout,
                    )
                    result = name, response
                except TimeoutError:
                    logger.warning("Agent '%s' timed out after %ds", name, _timeout)
                    _journal = ctx.get("_agent_journal")
                    if _journal is not None:
                        try:
                            await _journal.log_action(
                                agent_name=name,
                                action_text=f"Handled query: {query[:100]}",
                                outcome="timeout",
                            )
                        except Exception:
                            logger.debug("AgentJournal.log_action (timeout) failed for %s", name)
                    result = name, f"(Agent '{name}' timed out after {_timeout}s)"
                except (ToolExecutionError, Exception):
                    logger.exception("Agent '%s' failed", name)
                    _journal = ctx.get("_agent_journal")
                    if _journal is not None:
                        try:
                            await _journal.log_action(
                                agent_name=name,
                                action_text=f"Handled query: {query[:100]}",
                                outcome="error",
                            )
                        except Exception:
                            logger.debug("AgentJournal.log_action (error) failed for %s", name)
                    result = name, f"(Agent '{name}' encountered an error)"
                if on_progress:
                    await on_progress(
                        {"type": "agent_done", "agent": result[0], "preview": result[1][:200]}
                    )
                return result

        results = await asyncio.gather(
            *[_run_agent(name) for name in agent_names],
            return_exceptions=True,
        )
        for item in results:
            if isinstance(item, BaseException):
                logger.exception("Agent gather failed: %s", item)
                continue
            name, resp = item
            responses[name] = resp
        return responses

    def _parse_agent_list(self, routing_response: Any) -> list[str]:
        """Try to extract agent names from Athena response payloads.

        Accepts string JSON/plain text as well as direct dict/list payloads.
        """
        raw = routing_response
        text = ""
        data: Any | None = None

        if isinstance(raw, (dict, list)):
            data = raw
            text = json.dumps(raw, default=str)
        elif isinstance(raw, str):
            text = raw.strip()
            if text:
                try:
                    data = json.loads(text)
                except json.JSONDecodeError:
                    data = None
        elif raw is not None:
            text = str(raw)

        def _normalize_names(names: Any) -> list[str]:
            if isinstance(names, str):
                candidates: list[Any] = [names]
            elif isinstance(names, list):
                candidates = names
            else:
                return []
            out: list[str] = []
            for n in candidates:
                if not isinstance(n, str):
                    continue
                key = n.lower().strip()
                if key in self._agents and key not in out:
                    out.append(key)
            return out

        # Structured payload: {"agents":[...]} or {"agent":"..."}
        if isinstance(data, dict):
            out = _normalize_names(data.get("agents"))
            if out:
                return out
            out = _normalize_names(data.get("agent"))
            if out:
                return out

        # Structured payload: ["athena", "clio"] / mixed list payloads
        if isinstance(data, list):
            out = _normalize_names(data)
            if out:
                return out

        # Fallback: find known agent names mentioned in the text blob
        lower = text.lower()
        found = [name for name in self._agents if name in lower]
        if found:
            return found

        logger.debug(
            "Athena routing response could not be parsed into agents; falling back to athena.",
        )
        # Last resort: let Athena handle the query alone so we still return an answer
        return ["athena"]

    # ── skill execution ──────────────────────────────────────────────────

    async def use_skill(self, skill_name: str, **kwargs: Any) -> str:
        """Execute a skill by name at the orchestrator level.

        This is a convenience wrapper so callers that hold a reference to
        the Pantheon (e.g. the CLI or an API layer) can invoke skills
        without going through a specific agent.
        """
        logger.info("Pantheon invoking skill '%s'", skill_name)
        return await use_skill(skill_name, **kwargs)

    @staticmethod
    def available_skills() -> dict[str, str]:
        """Return the full skill matrix for introspection."""
        return dict(SKILL_MATRIX)

    # ── introspection ────────────────────────────────────────────────────

    @property
    def agents(self) -> dict[str, BaseAgent]:
        return dict(self._agents)

    def get_agent(self, name: str) -> BaseAgent | None:
        return self._agents.get(name)
