"""Centralised Pydantic settings for Brain OS.

Prefer :func:`get_settings` (and nested config objects) for application code so
defaults, env aliases, and validation stay in one place. Use ``os.environ``
only for early bootstrap or tests that must run before settings load.

Domain modules live under :mod:`brain_os.config` (MOVE split of the former monolith).
"""

from __future__ import annotations

from brain_os.config.app import AppConfig
from brain_os.config.common import EmailMode
from brain_os.config.data_paths import data_root, knowledge_path, resolve_under_data_root
from brain_os.config.google import GoogleConfig
from brain_os.config.integrations import (
    ApolloConfig,
    BoardConfig,
    DocumentAIConfig,
    ExternalAPIsConfig,
    FirecrawlConfig,
    HonchoConfig,
    JinaConfig,
    LangfuseConfig,
    DemoCampaignCampaignConfig,
    PdfCoConfig,
    PeopleDataLabsConfig,
    SearchConfig,
    SentryConfig,
    SlackConfig,
    TwentyConfig,
    UnstructuredConfig,
    VapiConfig,
    WhatsAppConfig,
    WolframConfig,
)
from brain_os.config.llm import EmbeddingConfig, HeliconeConfig, LLMConfig, LLMEndpointsConfig
from brain_os.config.settings import Settings, get_settings, secrets
from brain_os.config.storage import (
    DatabaseConfig,
    MemoryConfig,
    Neo4jConfig,
    QdrantConfig,
    RedisConfig,
)

# Phase 6/8: ops snapshots in config_ops_snapshots — full re-export for backward compatibility.
from brain_os.config_ops_snapshots import (
    get_app_feature_flags_public_snapshot,
    get_app_runtime_imports_public_snapshot,
    get_crm_database_public_snapshot,
    get_email_ops_public_snapshot,
    get_email_training_public_snapshot,
    get_event_driven_ingestion_public_snapshot,
    get_governance_brain_public_snapshot,
    get_graph_store_public_snapshot,
    get_http_api_public_snapshot,
    get_ingestion_brain_public_snapshot,
    get_knowledge_store_public_snapshot,
    get_llm_stack_public_snapshot,
    get_mem0_public_snapshot,
    get_neo4j_connection_flags_public_snapshot,
    get_optional_tooling_imports_public_snapshot,
    get_pipeline_observability_public_snapshot,
    get_pipeline_runtime_public_snapshot,
    get_process_context_public_snapshot,
    get_quality_stack_imports_public_snapshot,
    get_redis_cache_public_snapshot,
    get_repo_brain_aux_public_snapshot,
    get_repo_framework_public_snapshot,
    get_repo_sources_public_snapshot,
    get_repo_truth_hints_public_snapshot,
    get_repo_vcs_public_snapshot,
    get_runtime_build_public_snapshot,
    get_runtime_capabilities_public_snapshot,
    get_sales_coaching_brain_public_snapshot,
    get_secondary_google_oauth_public_snapshot,
    get_secondary_mail_public_snapshot,
    get_skills_registry_public_snapshot,
    get_storage_clients_public_snapshot,
    get_tracing_public_snapshot,
    get_vendor_apis_public_snapshot,
    get_workspace_content_public_snapshot,
    infer_http_health_status,
)

__all__ = [
    "ApolloConfig",
    "AppConfig",
    "BoardConfig",
    "DatabaseConfig",
    "DocumentAIConfig",
    "EmailMode",
    "EmbeddingConfig",
    "ExternalAPIsConfig",
    "FirecrawlConfig",
    "GoogleConfig",
    "HeliconeConfig",
    "HonchoConfig",
    "JinaConfig",
    "LLMConfig",
    "LLMEndpointsConfig",
    "LangfuseConfig",
    "MemoryConfig",
    "DemoCampaignCampaignConfig",
    "Neo4jConfig",
    "PdfCoConfig",
    "PeopleDataLabsConfig",
    "QdrantConfig",
    "RedisConfig",
    "SearchConfig",
    "SentryConfig",
    "Settings",
    "SlackConfig",
    "TwentyConfig",
    "UnstructuredConfig",
    "VapiConfig",
    "WhatsAppConfig",
    "WolframConfig",
    "data_root",
    "get_app_feature_flags_public_snapshot",
    "get_app_runtime_imports_public_snapshot",
    "get_crm_database_public_snapshot",
    "get_email_ops_public_snapshot",
    "get_email_training_public_snapshot",
    "get_event_driven_ingestion_public_snapshot",
    "get_governance_brain_public_snapshot",
    "get_graph_store_public_snapshot",
    "get_http_api_public_snapshot",
    "get_ingestion_brain_public_snapshot",
    "get_knowledge_store_public_snapshot",
    "get_llm_stack_public_snapshot",
    "get_mem0_public_snapshot",
    "get_neo4j_connection_flags_public_snapshot",
    "get_optional_tooling_imports_public_snapshot",
    "get_pipeline_observability_public_snapshot",
    "get_pipeline_runtime_public_snapshot",
    "get_process_context_public_snapshot",
    "get_quality_stack_imports_public_snapshot",
    "get_redis_cache_public_snapshot",
    "get_repo_brain_aux_public_snapshot",
    "get_repo_framework_public_snapshot",
    "get_repo_sources_public_snapshot",
    "get_repo_truth_hints_public_snapshot",
    "get_repo_vcs_public_snapshot",
    "get_runtime_build_public_snapshot",
    "get_runtime_capabilities_public_snapshot",
    "get_sales_coaching_brain_public_snapshot",
    "get_secondary_google_oauth_public_snapshot",
    "get_secondary_mail_public_snapshot",
    "get_settings",
    "get_skills_registry_public_snapshot",
    "get_storage_clients_public_snapshot",
    "get_tracing_public_snapshot",
    "get_vendor_apis_public_snapshot",
    "get_workspace_content_public_snapshot",
    "infer_http_health_status",
    "knowledge_path",
    "resolve_under_data_root",
    "secrets",
]

# Ensure AppConfig / nested configs remain importable from brain_os.config
# (historical: ``from brain_os.config import AppConfig, LLMConfig, ...``).
